twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        allCategories: '@App\Repository\CategoryRepository'
        allPrograms: '@App\Repository\ProgramRepository'

when@test:
    twig:
        strict_variables: true
